"""added new table

Revision ID: 395ee218029d
Revises: faa6761e3da5
Create Date: 2025-05-31 03:00:47.298361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395ee218029d'
down_revision: Union[str, None] = 'faa6761e3da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_rentals', sa.Column('hire_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_rentals', 'hire_date')
    # ### end Alembic commands ###
