"""add year column to Car

Revision ID: b5760ce6b381
Revises: e344c4fb6a77
Create Date: 2025-06-02 16:52:13.534277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5760ce6b381'
down_revision: Union[str, None] = 'e344c4fb6a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('color', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('rental_price', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('available', sa.Boolean(), nullable=True))
    op.drop_column('cars', 'make_year')
    op.drop_column('cars', 'license_plate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('license_plate', sa.VARCHAR(), nullable=True))
    op.add_column('cars', sa.Column('make_year', sa.INTEGER(), nullable=True))
    op.drop_column('cars', 'available')
    op.drop_column('cars', 'rental_price')
    op.drop_column('cars', 'mileage')
    op.drop_column('cars', 'color')
    op.drop_column('cars', 'year')
    # ### end Alembic commands ###
