"""remove column table

Revision ID: d933bbfa2770
Revises: 147514ff3d51
Create Date: 2025-05-31 03:02:21.048688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd933bbfa2770'
down_revision: Union[str, None] = '147514ff3d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_rentals', 'hire_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_rentals', sa.Column('hire_date', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
